import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.170.0/build/three.module.js';
import {OrbitControls} from 'https://cdn.jsdelivr.net/npm/three@0.170.0/examples/jsm/controls/OrbitControls.js';

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={page:'radiation',ray:'alpha',shield:'paper',decay:'alpha',reaction:'fission',motion:true,score:+localStorage.getItem('nqScore')||0,completed:JSON.parse(localStorage.getItem('nqCompleted')||'[]'),challenge:0};
const save=()=>{localStorage.setItem('nqScore',state.score);localStorage.setItem('nqCompleted',JSON.stringify(state.completed));$('#score').textContent=state.score;updateProgress()};
const toast=(text)=>{const t=$('#toast');t.textContent=text;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),2200)};
const reward=(id,points=10)=>{if(!state.completed.includes(id)){state.completed.push(id);state.score+=points;save();toast(`สำเร็จ! +${points} คะแนน`)}else toast('ภารกิจนี้ผ่านแล้ว')};
$('#score').textContent=state.score;

const storedName=localStorage.getItem('nqName')||'';$('#studentName').value=storedName;
$('#saveName').onclick=()=>{localStorage.setItem('nqName',$('#studentName').value.trim());toast('บันทึกชื่อแล้ว')};

// Three.js scene
const host=$('#scene'),scene=new THREE.Scene();scene.fog=new THREE.Fog(0x07111f,12,42);
const camera=new THREE.PerspectiveCamera(52,host.clientWidth/host.clientHeight,.1,100);camera.position.set(0,4.5,13);
const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(host.clientWidth,host.clientHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;host.appendChild(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=6;controls.maxDistance=22;controls.target.set(0,0,0);
scene.add(new THREE.HemisphereLight(0x77cfff,0x130923,2));const key=new THREE.PointLight(0xa66cff,60,35);key.position.set(5,7,8);scene.add(key);const rim=new THREE.PointLight(0x39e5ff,50,30);rim.position.set(-6,2,-4);scene.add(rim);
const floor=new THREE.Mesh(new THREE.CylinderGeometry(8,8,.35,64),new THREE.MeshStandardMaterial({color:0x0b1c30,metalness:.5,roughness:.55}));floor.position.y=-3.25;scene.add(floor);
const grid=new THREE.GridHelper(15,20,0x2e8ead,0x17304b);grid.position.y=-3.05;scene.add(grid);
const world=new THREE.Group();scene.add(world);
const sphere=(r,color,emissive=0)=>new THREE.Mesh(new THREE.SphereGeometry(r,24,24),new THREE.MeshStandardMaterial({color,roughness:.35,metalness:.18,emissive}));
function clearWorld(){while(world.children.length){const o=world.children.pop();o.traverse?.(x=>{x.geometry?.dispose();if(x.material){(Array.isArray(x.material)?x.material:[x.material]).forEach(m=>m.dispose())}})}}
function nucleus(count=42,scale=1){const g=new THREE.Group();for(let i=0;i<count;i++){const p=sphere(.29*scale,i%2?0xff607b:0x50d9ff,i%2?0x310008:0x002735);const r=1.45*scale*Math.cbrt(Math.random()),a=Math.random()*Math.PI*2,b=Math.acos(2*Math.random()-1);p.position.set(r*Math.sin(b)*Math.cos(a),r*Math.sin(b)*Math.sin(a),r*Math.cos(b));g.add(p)}return g}
let particles=[],shieldMesh,detector,mainNucleus;
const radCfg={alpha:{name:'รังสีแอลฟา (α)',desc:'อนุภาคฮีเลียม มีประจุ +2 มวลมาก ก่อไอออนสูง แต่ทะลุผ่านต่ำ',color:0xffcb58,count:26,speed:.045,pass:{none:1,paper:.02,aluminum:0,lead:0}},beta:{name:'รังสีบีตา (β⁻)',desc:'อิเล็กตรอนพลังงานสูง มีประจุ −1 ทะลุกระดาษได้ แต่อะลูมิเนียมช่วยกั้น',color:0x55efff,count:34,speed:.075,pass:{none:1,paper:.9,aluminum:.05,lead:.01}},gamma:{name:'รังสีแกมมา (γ)',desc:'คลื่นแม่เหล็กไฟฟ้าพลังงานสูง ไม่มีมวลและประจุ ต้องใช้ตะกั่วหรือคอนกรีตลดความเข้ม',color:0xc985ff,count:44,speed:.11,pass:{none:1,paper:.98,aluminum:.86,lead:.18}}};
function buildRadiation(){clearWorld();particles=[];mainNucleus=nucleus(44,1);mainNucleus.position.x=-3;world.add(mainNucleus);const mat=new THREE.MeshPhysicalMaterial({color:state.shield==='paper'?0xe9dfbd:state.shield==='aluminum'?0xb6c9dd:state.shield==='lead'?0x566275:0x28425b,transparent:true,opacity:state.shield==='none'?.08:state.shield==='paper'?.28:state.shield==='aluminum'?.5:.78,roughness:.25});shieldMesh=new THREE.Mesh(new THREE.BoxGeometry(.35,5,5),mat);shieldMesh.position.x=1;world.add(shieldMesh);detector=new THREE.Mesh(new THREE.CylinderGeometry(.9,.9,2.2,30),new THREE.MeshStandardMaterial({color:0x253b4f,metalness:.75,roughness:.3,emissive:0x001b24}));detector.rotation.z=Math.PI/2;detector.position.x=5;world.add(detector);const cfg=radCfg[state.ray];for(let i=0;i<cfg.count;i++){const d=sphere(state.ray==='alpha'?.11:.075,cfg.color,cfg.color);d.position.set(-1.8,(Math.random()-.5)*2.7,(Math.random()-.5)*2.7);d.userData={speed:cfg.speed*(.75+Math.random()*.5),willPass:Math.random()<cfg.pass[state.shield]};world.add(d);particles.push(d)}updateRadiationUI()}
function updateRadiationUI(){const cfg=radCfg[state.ray],rate=Math.round(1200*cfg.pass[state.shield]);$('#cpm').textContent=`${rate} CPM`;$('#meterFill').style.width=`${Math.min(100,rate/12)}%`;$('#radiationInfo').innerHTML=`<strong>${cfg.name}</strong>${cfg.desc}<br><small>ผลการจำลอง: ${rate>800?'ผ่านได้มาก':rate>100?'ผ่านได้บางส่วน':'ถูกกั้นเกือบทั้งหมด'}</small>`}

function buildHalfLife(){clearWorld();mainNucleus=nucleus(65,1.1);world.add(mainNucleus);const ring=new THREE.Mesh(new THREE.TorusGeometry(3.2,.045,10,80),new THREE.MeshBasicMaterial({color:0x4de2ff,transparent:true,opacity:.45}));ring.rotation.x=Math.PI/2;world.add(ring)}
function buildEquation(){clearWorld();mainNucleus=nucleus(48,1);mainNucleus.position.x=-2.5;world.add(mainNucleus);const arrow=new THREE.ArrowHelper(new THREE.Vector3(1,0,0),new THREE.Vector3(-.5,0,0),3,0x4de2ff,.5,.28);world.add(arrow);const daughter=nucleus(38,.82);daughter.position.x=3.5;world.add(daughter);if(state.decay!=='gamma'){const emitted=sphere(state.decay==='alpha'?.55:.22,state.decay==='alpha'?0xffcb58:0x9b6cff,state.decay==='alpha'?0x392500:0x21003c);emitted.position.set(2,1.8,0);world.add(emitted)}}
function buildReaction(){clearWorld();if(state.reaction==='fission'){const u=nucleus(72,1.15);u.position.x=-1.8;world.add(u);for(let i=0;i<3;i++){const n=sphere(.14,0x7fe8ff,0x155c66);n.position.set(3+i*.7,(i-1)*.7,0);n.userData.fly=true;n.userData.v=.025+i*.006;world.add(n)}const neutron=sphere(.16,0x7fe8ff,0x155c66);neutron.position.x=-5;neutron.userData.incoming=true;world.add(neutron)}else{const d=nucleus(3,.75),t=nucleus(4,.75);d.position.x=-2.5;t.position.x=2.5;d.userData.fuse=1;t.userData.fuse=-1;world.add(d,t)}}
function buildApplications(){clearWorld();const atom=nucleus(30,.9);world.add(atom);for(let i=0;i<5;i++){const orbit=new THREE.Mesh(new THREE.TorusGeometry(2.2+i*.35,.022,8,80),new THREE.MeshBasicMaterial({color:i%2?0x9b6cff:0x4de2ff,transparent:true,opacity:.45}));orbit.rotation.set(Math.random()*Math.PI,Math.random()*Math.PI,0);world.add(orbit)}}
function buildSafety(){clearWorld();const source=nucleus(30,.75);source.position.x=-3.5;world.add(source);const wall=new THREE.Mesh(new THREE.BoxGeometry(.65,4.8,4.8),new THREE.MeshStandardMaterial({color:0x596574,metalness:.7,roughness:.4}));wall.position.x=0;world.add(wall);const person=new THREE.Group();const head=sphere(.55,0x73ddff);head.position.y=1.2;const body=new THREE.Mesh(new THREE.CapsuleGeometry(.55,1.7,8,16),new THREE.MeshStandardMaterial({color:0x8a69e8}));person.add(head,body);person.position.x=3.5;world.add(person)}
function setScene(page){if(page==='radiation')buildRadiation();else if(page==='halfLife')buildHalfLife();else if(page==='equations')buildEquation();else if(page==='reactions')buildReaction();else if(page==='applications')buildApplications();else buildSafety()}

function animate(){requestAnimationFrame(animate);controls.update();if(state.motion){world.rotation.y+=.0012;if(mainNucleus)mainNucleus.rotation.y+=.006;particles.forEach(p=>{p.position.x+=p.userData.speed;if(p.position.x>1&& !p.userData.willPass)p.position.x=-1.8;if(p.position.x>5.5){p.position.set(-1.8,(Math.random()-.5)*2.7,(Math.random()-.5)*2.7)}});world.children.forEach(o=>{if(o.userData.incoming){o.position.x+=.035;if(o.position.x>-2.4)o.position.x=-5}if(o.userData.fly){o.position.x+=o.userData.v;if(o.position.x>7)o.position.x=1.5}if(o.userData.fuse){o.position.x+=.012*o.userData.fuse;if(Math.abs(o.position.x)<.35)o.position.x=2.5*o.userData.fuse}})}renderer.render(scene,camera)}animate();
addEventListener('resize',()=>{camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();renderer.setSize(host.clientWidth,host.clientHeight)});
$('#resetCamera').onclick=()=>{camera.position.set(0,4.5,13);controls.target.set(0,0,0);controls.update()};$('#toggleMotion').onclick=e=>{state.motion=!state.motion;e.currentTarget.textContent=state.motion?'⏸ หยุดการเคลื่อนไหว':'▶ เล่นการเคลื่อนไหว'};

// Navigation
$$('.nav-btn').forEach(b=>b.onclick=()=>{state.page=b.dataset.page;$$('.nav-btn').forEach(x=>x.classList.toggle('active',x===b));$$('.page').forEach(p=>p.classList.toggle('active',p.dataset.pagePanel===state.page));setScene(state.page);if(innerWidth<980)$('.panel-column').scrollIntoView({behavior:'smooth',block:'start'})});
$$('[data-rad]').forEach(b=>b.onclick=()=>{state.ray=b.dataset.rad;$$('[data-rad]').forEach(x=>x.classList.toggle('active',x===b));buildRadiation()});
$$('[data-shield]').forEach(b=>b.onclick=()=>{state.shield=b.dataset.shield;$$('[data-shield]').forEach(x=>x.classList.toggle('active',x===b));buildRadiation()});
$('#radiationTask').onclick=()=>{const ok=(state.ray==='alpha'&&['paper','aluminum','lead'].includes(state.shield))||(state.ray==='beta'&&['aluminum','lead'].includes(state.shield))||(state.ray==='gamma'&&state.shield==='lead');ok?reward('radiation'):toast('ลองเลือกวัสดุที่เหมาะกับรังสีชนิดนั้น')};

// Half-life
const isotopes=[{id:'C-14',half:5730,unit:'ปี',use:'หาอายุซากสิ่งมีชีวิต'},{id:'I-131',half:8.02,unit:'วัน',use:'ตรวจและรักษาโรคไทรอยด์'},{id:'Co-60',half:5.27,unit:'ปี',use:'รังสีรักษาและฆ่าเชื้อ'},{id:'Cs-137',half:30.17,unit:'ปี',use:'งานอุตสาหกรรมและสอบเทียบ'},{id:'P-32',half:14.3,unit:'วัน',use:'สารติดตามทางชีววิทยา'}];
$('#isotope').innerHTML=isotopes.map((x,i)=>`<option value="${i}">${x.id} — ${x.use}</option>`).join('');
const ctx=$('#chart').getContext('2d');
function drawHalfLife(){const iso=isotopes[+$('#isotope').value],N0=Math.max(1,+$('#n0').value||1),t=+$('#time').value,N=N0*Math.pow(.5,t/iso.half);$('#time').max=iso.half*5;$('#timeValue').textContent=t.toFixed(t<10?1:0);$('#halfLifeValue').textContent=`${iso.half} ${iso.unit}`;$('#remaining').textContent=N.toLocaleString('th-TH',{maximumFractionDigits:2});$('#decayed').textContent=(N0-N).toLocaleString('th-TH',{maximumFractionDigits:2});$('#percent').textContent=`${(N/N0*100).toFixed(2)}%`;const w=$('#chart').width,h=$('#chart').height;ctx.clearRect(0,0,w,h);ctx.strokeStyle='#24455f';ctx.lineWidth=1;for(let i=0;i<=5;i++){const x=45+i*(w-70)/5;ctx.beginPath();ctx.moveTo(x,20);ctx.lineTo(x,h-40);ctx.stroke()}ctx.strokeStyle='#4de2ff';ctx.lineWidth=4;ctx.beginPath();for(let i=0;i<=200;i++){const x=45+i*(w-70)/200,y=20+(1-Math.pow(.5,i/40))*(h-65);i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.stroke();const ratio=t/(iso.half*5),x=45+ratio*(w-70),y=20+(1-Math.pow(.5,t/iso.half))*(h-65);ctx.fillStyle='#9b6cff';ctx.beginPath();ctx.arc(x,y,8,0,Math.PI*2);ctx.fill();ctx.fillStyle='#eef7ff';ctx.font='16px Prompt';ctx.fillText('ปริมาณสารที่เหลือเทียบกับเวลา',48,20)}
$('#isotope').onchange=()=>{$('#time').value=0;drawHalfLife()};$('#n0').oninput=drawHalfLife;$('#time').oninput=drawHalfLife;drawHalfLife();
$('#halfLifeTask').onclick=()=>{const n=1+Math.floor(Math.random()*4),start=[80,160,320,640][Math.floor(Math.random()*4)],ans=start/2**n,q=$('#halfLifeQuestion');q.classList.remove('hidden');q.innerHTML=`<b>สารเริ่มต้น ${start} กรัม ผ่านไป ${n} ครึ่งชีวิต จะเหลือเท่าใด?</b><div class="quiz-options">${[ans,ans*2,ans/2,start-ans].sort(()=>Math.random()-.5).map(v=>`<button data-answer="${v===ans}">${v} กรัม</button>`).join('')}</div>`;q.querySelectorAll('button').forEach(b=>b.onclick=()=>{const ok=b.dataset.answer==='true';b.classList.add(ok?'correct':'wrong');ok?reward('halfLife'):toast('ทุกหนึ่งครึ่งชีวิต ปริมาณจะเหลือครึ่งหนึ่ง')})};

// Nuclear equations
const decayData={alpha:{title:'การสลายแอลฟา',eq:'²³⁸₉₂U → ²³⁴₉₀Th + ⁴₂He',mass:'A ลดลง 4',atomic:'Z ลดลง 2'},betaMinus:{title:'การสลายบีตาลบ',eq:'¹⁴₆C → ¹⁴₇N + ⁰₋₁e',mass:'A คงเดิม',atomic:'Z เพิ่มขึ้น 1'},betaPlus:{title:'การสลายบีตาบวก',eq:'²²₁₁Na → ²²₁₀Ne + ⁰₊₁e',mass:'A คงเดิม',atomic:'Z ลดลง 1'},gamma:{title:'การแผ่แกมมา',eq:'⁹⁹ᵐ₄₃Tc → ⁹⁹₄₃Tc + γ',mass:'A คงเดิม',atomic:'Z คงเดิม'},capture:{title:'การจับอิเล็กตรอน',eq:'⁷₄Be + ⁰₋₁e → ⁷₃Li',mass:'A คงเดิม',atomic:'Z ลดลง 1'}};
function updateDecay(){const d=decayData[state.decay];$('#equationDemo').innerHTML=`<small>${d.title}</small><br><b>${d.eq}</b>`;$('#massRule').textContent=d.mass;$('#atomicRule').textContent=d.atomic;buildEquation();makeEquationQuiz()}
$$('[data-decay]').forEach(b=>b.onclick=()=>{state.decay=b.dataset.decay;$$('[data-decay]').forEach(x=>x.classList.toggle('active',x===b));updateDecay()});
function makeEquationQuiz(){const qs=[{q:'เมื่อเกิดการสลายแอลฟา เลขมวลเปลี่ยนอย่างไร?',a:'ลดลง 4',o:['ลดลง 4','เพิ่มขึ้น 4','คงเดิม','ลดลง 2']},{q:'การสลายบีตาลบทำให้เลขอะตอมเปลี่ยนอย่างไร?',a:'เพิ่มขึ้น 1',o:['เพิ่มขึ้น 1','ลดลง 1','ลดลง 2','คงเดิม']},{q:'รังสีชนิดใดไม่ทำให้ A และ Z เปลี่ยน?',a:'แกมมา',o:['แอลฟา','บีตาลบ','แกมมา','บีตาบวก']}],x=qs[Math.floor(Math.random()*qs.length)];$('#equationQuiz').innerHTML=`<b>${x.q}</b><div class="quiz-options">${x.o.map(v=>`<button data-answer="${v===x.a}">${v}</button>`).join('')}</div>`;$('#equationQuiz').querySelectorAll('button').forEach(b=>b.onclick=()=>{const ok=b.dataset.answer==='true';b.classList.add(ok?'correct':'wrong');ok?reward('equations'):toast('ตรวจสอบการอนุรักษ์เลขมวลและเลขอะตอม')})}
$('#newEquation').onclick=makeEquationQuiz;updateDecay();

// Reactions
const reactionText={fission:'<strong>นิวเคลียร์ฟิชชัน</strong>นิวเคลียสหนัก เช่น U-235 รับนิวตรอนแล้วแตกเป็นนิวเคลียสที่เล็กลง พร้อมปล่อยพลังงานและนิวตรอน ซึ่งอาจทำให้เกิดปฏิกิริยาลูกโซ่',fusion:'<strong>นิวเคลียร์ฟิวชัน</strong>นิวเคลียสเบารวมกันเป็นนิวเคลียสที่หนักขึ้น เช่น ดิวเทอเรียมรวมกับทริเทียม ต้องใช้อุณหภูมิสูงมากและให้พลังงานมหาศาล'};
function updateReaction(){$('#reactionText').innerHTML=reactionText[state.reaction];buildReaction()}
$$('[data-reaction]').forEach(b=>b.onclick=()=>{state.reaction=b.dataset.reaction;$$('[data-reaction]').forEach(x=>x.classList.toggle('active',x===b));updateReaction()});$('#energy').oninput=e=>$('#energyValue').textContent=e.target.value;$('#launchReaction').onclick=()=>{const en=+$('#energy').value;if(state.reaction==='fusion'&&en<75)return toast('ฟิวชันต้องการพลังงาน/อุณหภูมิเริ่มต้นสูงมาก');buildReaction();reward('reactions');toast(state.reaction==='fission'?'เกิดฟิชชันและปล่อยนิวตรอน':'นิวเคลียสเบารวมตัวเป็นฮีเลียม')};updateReaction();

// Applications
const apps=[{iso:'I-131',icon:'🦋',title:'ไทรอยด์',text:'ใช้ตรวจและรักษาความผิดปกติของต่อมไทรอยด์'},{iso:'Co-60',icon:'🏥',title:'รังสีรักษา',text:'ใช้ฉายรังสีรักษามะเร็งและฆ่าเชื้ออุปกรณ์'},{iso:'C-14',icon:'🏺',title:'โบราณคดี',text:'ใช้ประมาณอายุซากสิ่งมีชีวิตในอดีต'},{iso:'P-32',icon:'🌱',title:'เกษตรและชีววิทยา',text:'ใช้เป็นสารติดตามการดูดซึมฟอสฟอรัส'},{iso:'Tc-99m',icon:'🫀',title:'เวชศาสตร์นิวเคลียร์',text:'ใช้สร้างภาพการทำงานของอวัยวะ'},{iso:'Am-241',icon:'🔥',title:'เครื่องตรวจจับควัน',text:'ใช้ไอออไนซ์อากาศในอุปกรณ์ตรวจจับควันบางชนิด'}];
$('#applicationCards').innerHTML=apps.map(x=>`<div class="application-card" tabindex="0"><b>${x.icon} ${x.iso}</b><span>${x.title}</span><p class="hidden">${x.text}</p></div>`).join('');$$('.application-card').forEach(c=>c.onclick=()=>c.querySelector('p').classList.toggle('hidden'));
function makeApplicationQuiz(){const x=apps[Math.floor(Math.random()*apps.length)],choices=[x,...apps.filter(a=>a!==x).sort(()=>Math.random()-.5).slice(0,3)].sort(()=>Math.random()-.5);$('#applicationQuiz').innerHTML=`<b>ไอโซโทปใดสัมพันธ์กับ “${x.title}”?</b><div class="quiz-options">${choices.map(v=>`<button data-answer="${v===x}">${v.iso}</button>`).join('')}</div>`;$('#applicationQuiz').querySelectorAll('button').forEach(b=>b.onclick=()=>{const ok=b.dataset.answer==='true';b.classList.add(ok?'correct':'wrong');ok?reward('applications'):toast('เปิดการ์ดความรู้เพื่อค้นหาคำตอบ')})}
$('#newApplication').onclick=makeApplicationQuiz;makeApplicationQuiz();

// Safety
function updateDose(){const time=+$('#exposureTime').value,d=+$('#distance').value,shield=+$('#safetyShield').value,dose=time*shield/(d*d);$('#exposureTimeValue').textContent=time;$('#distanceValue').textContent=d;$('#dose').textContent=dose.toFixed(2);$('#safetyAdvice').innerHTML=dose<1?'<strong>ระดับต่ำ</strong>การลดเวลา เพิ่มระยะทาง และใช้กำบังช่วยลดการรับรังสีได้ดี':dose<8?'<strong>ควรปรับปรุง</strong>เพิ่มระยะห่าง ลดเวลา หรือเลือกวัสดุกำบังที่มีประสิทธิภาพขึ้น':'<strong>ระดับสูงในแบบจำลอง</strong>ออกจากพื้นที่ ลดเวลา และเพิ่มการกำบังทันที'}
['exposureTime','distance','safetyShield'].forEach(id=>$('#'+id).oninput=updateDose);updateDose();$('#safetyTask').onclick=()=>+$('#dose').textContent<1?reward('safety'):toast('ทำให้ดัชนีต่ำกว่า 1 โดยใช้หลัก เวลา–ระยะทาง–กำบัง');

// Final challenge and progress
const challenges=[{q:'วัสดุใดเหมาะที่สุดในการลดรังสีแกมมา?',a:'ตะกั่ว',o:['กระดาษ','ผ้า','ตะกั่ว','พลาสติก']},{q:'ผ่านไป 3 ครึ่งชีวิต สารจะเหลือกี่ส่วนของเดิม?',a:'1/8',o:['1/2','1/4','1/8','1/16']},{q:'การสลายแอลฟาทำให้เลขมวลลดลงเท่าใด?',a:'4',o:['1','2','4','ไม่เปลี่ยน']},{q:'ข้อใดคือนิวเคลียร์ฟิวชัน?',a:'นิวเคลียสเบารวมกัน',o:['นิวเคลียสหนักแตกตัว','นิวเคลียสเบารวมกัน','ปล่อยอิเล็กตรอน','ปล่อยแกมมา']},{q:'หลักความปลอดภัยใดถูกต้อง?',a:'ลดเวลา เพิ่มระยะทาง ใช้กำบัง',o:['เพิ่มเวลา ลดระยะทาง','ลดเวลา เพิ่มระยะทาง ใช้กำบัง','สัมผัสแหล่งรังสีโดยตรง','ใช้กระดาษกั้นรังสีทุกชนิด']},{q:'C-14 นิยมใช้ในงานใด?',a:'หาอายุซากสิ่งมีชีวิต',o:['ผลิตไฟฟ้าโดยตรง','หาอายุซากสิ่งมีชีวิต','ตรวจจับควัน','รักษาไทรอยด์']}];
function updateProgress(){const n=['radiation','halfLife','equations','reactions','applications','safety'].filter(x=>state.completed.includes(x)).length;$('#progressText').textContent=`${n}/6 ภารกิจ`;$('#progressFill').style.width=`${n/6*100}%`;if(n===6){$('#certificate').classList.remove('hidden');$('#certificateName').textContent=localStorage.getItem('nqName')||'ผู้เรียน'}}
function nextChallenge(){if(state.challenge>=challenges.length){reward('final',30);$('#challengeBox').innerHTML='<b>ยอดเยี่ยม! คุณตอบภารกิจสรุปครบแล้ว</b>';$('#nextChallenge').textContent='ทำภารกิจใหม่';state.challenge=0;return}const x=challenges[state.challenge];$('#challengeBox').innerHTML=`<b>ข้อ ${state.challenge+1}/${challenges.length}: ${x.q}</b><div class="quiz-options">${x.o.map(v=>`<button data-answer="${v===x.a}">${v}</button>`).join('')}</div>`;$('#challengeBox').querySelectorAll('button').forEach(b=>b.onclick=()=>{const ok=b.dataset.answer==='true';b.classList.add(ok?'correct':'wrong');if(ok){state.score+=5;state.challenge++;save();setTimeout(nextChallenge,450)}else toast('ยังไม่ถูก ลองทบทวนบทเรียนอีกครั้ง')})}
$('#nextChallenge').onclick=nextChallenge;$('#resetProgress').onclick=()=>{if(confirm('ต้องการล้างคะแนนและความก้าวหน้าหรือไม่?')){state.score=0;state.completed=[];localStorage.removeItem('nqScore');localStorage.removeItem('nqCompleted');save();$('#certificate').classList.add('hidden');toast('ล้างความก้าวหน้าแล้ว')}};$('#printCertificate').onclick=()=>print();updateProgress();

setScene('radiation');save();